AllCops:
  Exclude:
    - 'lib/**/*'

Lint/Void:
  Exclude:
    - 'features/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'features/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 2

Style/ClassVars:
  Exclude:
    - 'features/**/*'