Lint/Void:
  Exclude:
    - 'features/**/*'

Metrics/AbcSize:
  Max: 16
  Exclude:
    - 'features/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Exclude:
    - app/controllers/**/*

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'features/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'features/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'features/**/*'

Style/BlockComments:
  Exclude:
    - app/controllers/**/*

Style/Documentation:
  Exclude:
    - 'features/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 2

Style/ClassVars:
  Exclude:
    - 'features/**/*'