Metrics/AbcSize:
  Max: 16

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'features/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Exclude:
    - app/controllers/**/*

Style/BlockComments:
  Exclude:
    - app/controllers/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 2