#!/usr/bin/env ruby
# frozen_string_literal: true

self_dir = File.dirname(__FILE__)
bin = "#{self_dir}/../vendor/{gems,plugins}/cucumber*/bin/cucumber"
vendored_cucumber_bin = Dir[bin].first

if vendored_cucumber_bin
  load File.expand_path(vendored_cucumber_bin)
else
  require 'rubygems' unless ENV['NO_RUBYGEMS']
  require 'cucumber'
  load Cucumber::BINARY
end
